

_LAIXIA_EVENT_UPDATAGOLD = "_LAIXIA_EVENT_UPDATAGOLD" --更新金币

-- 返回ID
_LAIXIA_EVENT_RETURN_BACK = "_LAIXIA_EVENT_RETURN_BACK"

-- 断线直接进入牌桌
_LAIXIA_EVENT_RECONNECTION_WINDOW = "_LAIXIA_EVENT_RECONNECTION_WINDOW"
-- 断线问询是否在牌桌
_LAIXIA_EVENT_ISONLINEROOM_WINDOW = "_LAIXIA_EVENT_ISONLINEROOM_WINDOW"

-- 心跳
_LAIXIA_EVENT_SEND_HEARTTICK_WINDOW = "_LAIXIA_EVENT_SEND_HEARTTICK_WINDOW"
--隐藏小游戏进度条
_LAIXIA_EVENT_HIDE_XIAOYOUXI_PEOGRESS = "_LAIXIA_EVENT_HIDE_XIAOYOUXI_PEOGRESS"

-- 加载界面
_LAIXIA_EVENT_SHOW_LOADIN_WINDOW = "_LAIXIA_EVENT_SHOW_LOADIN_WINDOW"

--退出游戏
_LAIXIA_EVENT_EXITGAME_WINDOW = "_LAIXIA_EVENT_EXITGAME_WINDOW"

--账号登陆
_LAIXIA_EVENT_SHOW_ACCOUNTLOGIN_WINDOW="_LAIXIA_EVENT_SHOW_ACCOUNTLOGIN_WINDOW"
_LAIXIA_EVENT_SENDLOGINPACKET_TOSEVER ="_LAIXIA_EVENT_SENDLOGINPACKET_TOSEVER"
--断网等待 圈圈
_LAIXIA_EVENT_SHOW_RECONNECTIONTIPS_WINDOW = "_LAIXIA_EVENT_SHOW_RECONNECTIONTIPS_WINDOW"
_LAIXIA_EVENT_HIDE_RECONNECTIONTIPS_WINDOW = "_LAIXIA_EVENT_HIDE_RECONNECTIONTIPS_WINDOW"

--发送获取功能开关消息
_LAIXIA_EVENT_SEND_VERSIONOPEN_WINDOW = "_LAIXIA_EVENT_SEND_VERSIONOPEN_WINDOW"

--提示跳转
_LAIXIA_EVENT_SHOW_MARKEDJUMP_WINDOW="_LAIXIA_EVENT_SHOW_MARKEDJUMP_WINDOW"
_LAIXIA_EVENT_HIDE_MARKEDJUMP_WINDOW="_LAIXIA_EVENT_HIDE_MARKEDJUMP_WINDOW"

-- 提示语
_LAIXIA_EVENT_SHOW_MARKEDWORDS_WINDOW = "_LAIXIA_EVENT_SHOW_MARKEDWORDS_WINDOW"
_LAIXIA_EVENT_HIDE_MARKEDWORDS_WINDOW = "_LAIXIA_EVENT_HIDE_MARKEDWORDS_WINDOW"

--提示语oTher
_LAIXIA_EVENT_SHOW_TISHIYUOTHER_WINDOW = "_LAIXIA_EVENT_SHOW_TISHIYUOTHER_WINDOW"

----------------------------------------------------------------------------------
--大厅自建房
_LAIXIA_EVENT_SHOW_SELFBUILDING_WINDOW = "_LAIXIA_EVENT_SHOW_SELFBUILDING_WINDOW"
_LAIXIA_EVENT_HIDE_SELFBUILDING_WINDOW = "_LAIXIA_EVENT_HIDE_SELFBUILDING_WINDOW"
_LAIXIA_EVENT_PACKET_CREATESELFBUILF =  "_LAIXIA_EVENT_PACKET_CREATESELFBUILF"

--牌桌自建桌的ui更新
_LAIXIA_EVENT_UPDATE_SELFBUILDINGUI = "_LAIXIA_EVENT_UPDATE_SELFBUILDINGUI"
--自建桌继续游戏的界面更新
_LAIXIA_EVENT_UPDATE_CONTINUESELFBUILD = "_LAIXIA_EVENT_UPDATE_CONTINUESELFBUILD" 
--自建桌有人退出界面的更新
_LAIXIA_ECENT_UPDATE_UIINEXIT = "_LAIXIA_ECENT_UPDATE_UIINEXIT"
_LAIXIA_EVENT_UPDATEGOLD = "_LAIXIA_EVENT_UPDATEGOLD"
----------------------------------------------------------------------------------
--领取推广金
_LAIXIA_EVENT_SHOW_EXTENSION_WINDOW = "_LAIXIA_EVENT_SHOW_EXTENSION_WINDOW"
_LAIXIA_EVENT_HIDE_EXTENSION_WINDOW = "_LAIXIA_EVENT_HIDE_EXTENSION_WINDOW"
_LAIXIA_EVENT_UPDATE_EXTENSION =  "_LAIXIA_EVENT_UPDATE_EXTENSION"

--礼包赠送服务
_LAIXIA_EVENT_SHOW_PRESENT_WINDOW = "_LAIXIA_EVENT_SHOW_PRESENT_WINDOW"
_LAIXIA_EVENT_HIDE_PRESENT_WINDOW = "_LAIXIA_EVENT_HIDE_PRESENT_WINDOW"

-- 飘字提示
_LAIXIA_EVENT_SHOW_FLOWWORDS_WINDOW ="_LAIXIA_EVENT_SHOW_FLOWWORDS_WINDOW"


-- 礼盒
_LAIXIA_EVENT_SHOW_TOOLSBOX_WINDOW="_LAIXIA_EVENT_SHOW_TOOLSBOX_WINDOW"
_LAIXIA_EVENT_UPDATE_TOOLBOX_WINDOW="_LAIXIA_EVENT_UPDATE_TOOLBOX_WINDOW"
_LAIXIA_EVENT_SEND_TOOLBOX_WINDOW = "_LAIXIA_EVENT_SEND_TOOLBOX_WINDOW"

--公共头
_LAIXIA_EVENT_SHOW_COMMONTOP_WINDOW="_LAIXIA_EVENT_SHOW_COMMONTOP_WINDOW"

-- 公共底
_LAIXIA_EVENT_SHOW_COMMONFLOOR_WINDOW="_LAIXIA_EVENT_SHOW_COMMONFLOOR_WINDOW"

--游戏类型
_LAIXIA_EVENT_SHOW_GAMETYPE_WINDOW = "_LAIXIA_EVENT_SHOW_GAMETYPE_WINDOW"

-- 主界面
_LAIXIA_EVENT_SHOW_MAININTERFACE_WINDOW = "_LAIXIA_EVENT_SHOW_MAININTERFACE_WINDOW"
_LAIXIA_EVENT_UPDATE_MAININTERFACE_WINDOW = "_LAIXIA_EVENT_UPDATE_MAININTERFACE_WINDOW"
_LAIXIA_EVENT_UPDATE_MAININTERFACE_TOP_WINDOW = "_LAIXIA_EVENT_UPDATE_MAININTERFACE_TOP_WINDOW"

-- 选桌界面数据
_LAIXIA_EVENT_UPDATE_SELECTROOM_WINDOW = "_LAIXIA_EVENT_UPDATE_SELECTROOM_WINDOW"

--请求个人信息
_LAIXIA_EVENT_SHOW_HALL_WINDOW = "_LAIXIA_EVENT_SHOW_HALL_WINDOW"
--显示站内信提示
_LAIXIA_EVENT_SHOW_LETTERRED_WINDOW = "_LAIXIA_EVENT_SHOW_LETTERRED_WINDOW"
--隐藏站内信提示
_LAIXIA_EVENT_HIDES_LETTERRED_WINDOW="_LAIXIA_EVENT_HIDES_LETTERRED_WINDOW"
--显示背包红点提示
_LAIXIA_EVENT_SHOW_BAGRED_WINDOW = "_LAIXIA_EVENT_SHOW_BAGRED_WINDOW"
--隐藏背包红点提示
_LAIXIA_EVENT_HIDES_BAGRED_WINDOW = "_LAIXIA_EVENT_HIDES_BAGRED_WINDOW"

--刷新大厅个人数据
_LAIXIA_EVENT_UPDATE_PERSONINFO_WINDOW = "_LAIXIA_EVENT_UPDATE_PERSONINFO_WINDOW"

-- 帮助
_LAIXIA_EVENT_SHOW_HELP_WINDOW = "_LAIXIA_EVENT_SHOW_HELP_WINDOW"
_LAIXIA_EVENT_HIDE_HELP_WINDOW = "_LAIXIA_EVENT_HIDE_HELP_WINDOW"

-- 公告
_LAIXIA_EVENT_SHOW_BULLETINS_WINDOW = "_LAIXIA_EVENT_SHOW_BULLETINS_WINDOW"
_LAIXIA_EVENT_UPDATE_BULLETINS_WINDOW = "_LAIXIA_EVENT_UPDATE_BULLETINS_WINDOW"
_LAIXIA_EVENT_REQUEST_BULLETINS_WINDOW = "_LAIXIA_EVENT_REQUEST_BULLETINS_WINDOW"

-- 广播
_LAIXIA_EVENT_SHOW_BROADCAST_WINDOW   = "_LAIXIA_EVENT_SHOW_BROADCAST_WINDOW"
_LAIXIA_EVENT_HIDE_BROADCAST_WINDOW   = "_LAIXIA_EVENT_HIDE_BROADCAST_WINDOW"
_LAIXIA_EVENT_SHIELD_BROADCAST_WINDOW = '_LAIXIA_EVENT_SHIELD_BROADCAST_WINDOW'

_LAIXIA_EVENT_SHOW_BROADCASTS_WINDOW   = "_LAIXIA_EVENT_SHOW_BROADCASTS_WINDOW"

-- 聊天
_LAIXIA_EVENT_SHOW_TALKING_WINDOW = "_LAIXIA_EVENT_SHOW_TALKING_WINDOW"
_LAIXIA_EVENT_HIDE_TALKING_WINDOW = "_LAIXIA_EVENT_HIDE_TALKING_WINDOW"
_LAIXIA_EVENT_SHOW_TALKINGINFO_WINDOW="_LAIXIA_EVENT_SHOW_TALKINGINFO_WINDOW"


_LAIXIA_EVENT_SHOW_COMPLAIN_WINDOW = "_LAIXIA_EVENT_SHOW_COMPLAIN_WINDOW"

-- 站内信
_LAIXIA_EVENT_SHOW_MAIL_WINDOW = "_LAIXIA_EVENT_SHOW_MAIL_WINDOW"
_LAIXIA_EVENT_UPDATE_MAIL_WINDOW = "_LAIXIA_EVENT_UPDATE_MAIL_WINDOW"

-- 手机登陆窗口
_LAIXIA_EVENT_SHOW_PHONELOGIN_WINDOW="_LAIXIA_EVENT_SHOW_PHONELOGIN_WINDOW"

-- 排行榜
_LAIXIA_EVENT_SHOW_RANK_WINDOW = "_LAIXIA_EVENT_SHOW_RANK_WINDOW"
_LAIXIA_EVENT_UPDATE_RANK_WINDOW = "_LAIXIA_EVENT_UPDATE_RANK_WINDOW"
_LAIXIA_EVENT_REQUEST_RANKLIST_WINDOW = "_LAIXIA_EVENT_REQUEST_RANKLIST_WINDOW"

-- 商城
_LAIXIA_EVENT_SHOW_SHOP_WINDOW = "_LAIXIA_EVENT_SHOW_SHOP_WINDOW"
_LAIXIA_EVENT_HIDE_SHOP_WINDOW = "_LAIXIA_EVENT_HIDE_SHOP_WINDOW"
_LAIXIA_EVENT_UPDATE_SHOP_WINDOW = "_LAIXIA_EVENT_UPDATE_SHOP_WINDOW"
_LAIXIA_EVENT_SEND_SHOPWINDOW = "_LAIXIA_EVENT_SEND_SHOPWINDOW"
--是否去商城提示框
_LAIXIA_EVENT_SHOW_TSGOSHOP_SHOPWINDOW = "_LAIXIA_EVENT_SHOW_TSGOSHOP_SHOPWINDOW"
--隐藏提示框
--_LAIXIA_EVENT_HIDE_TSGOSHOP_SHOPWINDOW = "_LAIXIA_EVENT_HIDE_TSGOSHOP_SHOPWINDOW"


--发送order订单请求
_LAIXIA_EVENT_SEND_ORDERINFO_WINDOW = "_LAIXIA_EVENT_SEND_ORDERINFO_WINDOW"

--斗地主兑换虚拟
_LAIXIA_EVENT_SHOW_REDEEMVIRTUAL_WINDOW = "_LAIXIA_EVENT_SHOW_REDEEMVIRTUAL_WINDOW"

--斗地主兑换实物
_LAIXIA_EVENT_SHOW_REDEEMENTITY_WINDOW = "_LAIXIA_EVENT_SHOW_REDEEMENTITY_WINDOW"

--兑换礼物
_LAIXIA_EVENT_SHOW_REDEEMGIFT_WINDOW="_LAIXIA_EVENT_SHOW_REDEEMGIFT_WINDOW"
_LAIXIA_EVENT_HIDE_REDEEMGIFT_WINDOW="_LAIXIA_EVENT_HIDE_REDEEMGIFT_WINDOW"

--兑换详情
_LAIXIA_EVENT_SHOW_REDEEMDETAILS_WINDOW="_LAIXIA_EVENT_SHOW_REDEEMDETAILS_WINDOW"

-- 玩家信息
_LAIXIA_EVENT_SHOW_USEINFO_WINDOW = "_LAIXIA_EVENT_SHOW_USEINFO_WINDOW"
_LAIXIA_EVENT_HIDE_USEINFO_WINDOW = "_LAIXIA_EVENT_HIDE_USEINFO_WINDOW"
_LAIXIA_EVENT_UPDATE_USERINFO_WINDOW = "_LAIXIA_EVENT_UPDATE_USERINFO_WINDOW"

-- 连续登陆
_LAIXIA_EVENT_SHOW_DAILYSIGN_WINDOW = "_LAIXIA_EVENT_SHOW_DAILYSIGN_WINDOW"
_LAIXIA_EVENT_HIDE_DAILYSIGN_WINDOW = "_LAIXIA_EVENT_HIDE_DAILYSIGN_WINDOW"
_LAIXIA_EVENT_SIGNIN_DAILYSIGN_WINDOW = "_LAIXIA_EVENT_SIGNIN_DAILYSIGN_WINDOW"
_LAIXIA_EVENT_SEND_QUICKBAG_WINDOW = "_LAIXIA_EVENT_SEND_QUICKBAG_WINDOW"


-- 绑定手机号
_LAIXIA_EVENT_SHOW_BINDPHONE_WINDOW = "_LAIXIA_EVENT_SHOW_BINDPHONE_WINDOW"
_LAIXIA_EVENT_HIDE_BINDPHONE_WINDOW = "_LAIXIA_EVENT_HIDE_BINDPHONE_WINDOW"

--绑定成功
_LAIXIA_EVENT_SHOW_BINDTRUE_WINDOW="_LAIXIA_EVENT_SHOW_BINDTRUE_WINDOW"

-- 修改密码
_LAIXIA_EVENT_SHOW_REVISEPASSWD_WINDOW = "_LAIXIA_EVENT_SHOW_REVISEPASSWD_WINDOW"
_LAIXIA_EVENT_HIDE_REVISEPASSWD_WINDOW = "_LAIXIA_EVENT_HIDE_REVISEPASSWD_WINDOW"

--找回密码
_LAIXIA_EVENT_SHOW_FINDPWD_WINDOW ="_LAIXIA_EVENT_SHOW_FINDPWD_WINDOW"
_LAIXIA_EVENT_HIDE_FINDPWD_WINDOW ="_LAIXIA_EVENT_HIDE_FINDPWD_WINDOW"

--修改性别昵称
_LAIXIA_EVENT_SUCCESS_REVISESEXNICK_WINDOW = "_LAIXIA_EVENT_SUCCESS_REVISESEXNICK_WINDOW"

-- 设置
_LAIXIA_EVENT_SHOW_SETUP_WINDOW = "_LAIXIA_EVENT_SHOW_SETUP_WINDOW"
_LAIXIA_EVENT_HIDE_SETUP_WINDOW = "_LAIXIA_EVENT_HIDE_SETUP_WINDOW"

-- 游戏说明
_LAIXIA_EVENT_SHOW_GAMEDESCRIBE_WINDOW = "_LAIXIA_EVENT_SHOW_GAMEDESCRIBE_WINDOW"

--大转盘
_LAIXIA_EVENT_SHOW_BIGTURNTABLE_WINDOW = "_LAIXIA_EVENT_SHOW_BIGTURNTABLE_WINDOW"
_LAIXIA_PACKET_ENTER_BIGTURNTABLE = "_LAIXIA_PACKET_ENTER_BIGTURNTABLE"
_LAIXIA_EVENT_SENDLOTTRYTMSG_TOTURNTABLE = "_LAIXIA_EVENT_SENDLOTTRYTMSG_TOTURNTABLE"
_LAIXIA_EVENT_DANMUMESG_TURNTABLE = "_LAIXIA_EVENT_DANMUMESG_TURNTABLE"
_LAIXIA_EVENT_REFRESH_TOTURNTABLE_PRICEINFO = "_LAIXIA_EVENT_REFRESH_TOTURNTABLE_PRICEINFO"

--恭喜获得界面
_LAIXIA_EVENT_SHOW_GAIN_WINDOW = "_LAIXIA_EVENT_SHOW_GAIN_WINDOW"

--周卡月卡购买界面
_LAIXIA_EVENT_SHOW_WEEKCARD_WINDOW = "_LAIXIA_EVENT_SHOW_WEEKCARD_WINDOW"

-- 首充礼包界面
_LAIXIA_EVENT_SHOW_FIRSTGIFT_WINDOW = "_LAIXIA_EVENT_SHOW_FIRSTGIFT_WINDOW"
_LAIXIA_EVENT_RETURN_FIRSTGIFT_WINDOW = "_LAIXIA_EVENT_RETURN_FIRSTGIFT_WINDOW"
_LAIXIA_EVENT_SENDPACKET_FIRSTGIFT = "_LAIXIA_EVENT_SENDPACKET_FIRSTGIFT"

_LAIXIA_EVENT_SHOW_NOMONEY_WINDOW = "_LAIXIA_EVENT_SHOW_NOMONEY_WINDOW"

-- 金币特效
_LAIXIA_EVENT_SHOW_EFFECTGOLD_WINDOW = "_LAIXIA_EVENT_SHOW_EFFECTGOLD_WINDOW"

-- 破产礼包bankrupt
_LAIXIA_EVENT_SHOW_BANKRUPTBAG_WINDOW = "_LAIXIA_EVENT_SHOW_BANKRUPTBAG_WINDOW"
_LAIXIA_EVENT_SEND_BANKRUPTBAG_WINDOW = "_LAIXIA_EVENT_SEND_BANKRUPTBAG_WINDOW"

-- 增加金币界面
_LAIXIA_EVENT_SHOW_INCREASEGOLD_WINDOW = "_LAIXIA_EVENT_SHOW_INCREASEGOLD_WINDOW"
_LAIXIA_EVENT_HIDE_INCREASEGOLD_WINDOW = "_LAIXIA_EVENT_HIDE_INCREASEGOLD_WINDOW"

-- 发送救济金请求
_LAIXIA_EVENT_SEND_RELIEF_WINDOW = "_LAIXIA_EVENT_SEND_RELIEF_WINDOW"
-- 救济金次数
_LAIXIA_EVENT_SEND_RELIEFINFO_WINDOW = "_LAIXIA_EVENT_SEND_RELIEFINFO_WINDOW"

--活动 充值
_LAIXIA_EVENT_SHOW_ACTIVITYGIFT_WINDOW = "_LAIXIA_EVENT_SHOW_ACTIVITYGIFT_WINDOW"

-- 兑换
_LAIXIA_EVENT_SEND_EXCHANGE_WINDOW = "_LAIXIA_EVENT_SEND_EXCHANGE_WINDOW"
_LAIXIA_EVENT_UPDATE_EXCHANGE_WINDOW="_LAIXIA_EVENT_UPDATE_EXCHANGE_WINDOW"
--sdk购买
_LAIXIA_EVENT_SHOW_PAY_WINDOW = "_LAIXIA_EVENT_SHOW_PAY_WINDOW"
_LAIXIA_EVENT_PAY_TOFUN = "_LAIXIA_EVENT_PAY_TOFUN" --直接购买
_LAIXIA_EVENT_PAY_WEIYOUXI = "_LAIXIA_EVENT_PAY_WEIYOUXI"
_LAIXIA_EVENT_PAY_XIAOMI = "_LAIXIA_EVENT_PAY_XIAOMI"


-- 大厅个人详情
_LAIXIA_EVENT_SHOW_LOBBYDETAILS_WINDOW="_LAIXIA_EVENT_SHOW_LOBBYDETAILS_WINDOW"

--头像图片 
_LAIXIA_EVENT_DOWNLOAD_PICTURE_WINDOW = "_LAIXIA_EVENT_DOWNLOAD_PICTURE_WINDOW"
_LAIXIA_EVENT_DOWNLOADLOBBY_PICTURE_WINDOW = "_LAIXIA_EVENT_DOWNLOADLOBBY_PICTURE_WINDOW"
_LAIXIA_EVENT_UPDATE_PICTURE_WINDOW = "_LAIXIA_EVENT_UPDATE_PICTURE_WINDOW"
_LAIXIA_EVENT_DOWNLOADRANK_PICTURE_WINDOW = "_LAIXIA_EVENT_DOWNLOADRANK_PICTURE_WINDOW"
_LAIXIA_EVENT_DOWNLOADPERSONAL_PICTURE_WINDOW = "_LAIXIA_EVENT_DOWNLOADPERSONAL_PICTURE_WINDOW"

_LAIXIA_EVENT_DOWNLOAD_SELFROOM_PERSONAL_PICTURE_WINDOW = "_LAIXIA_EVENT_DOWNLOAD_SELFROOM_PERSONAL_PICTURE_WINDOW"
_LAIXIA_EVENT_DOWNLOAD_RESULT_SMALL_PICTURE_WINDOW = "_LAIXIA_EVENT_DOWNLOAD_RESULT_SMALL_PICTURE_WINDOW"
_LAIXIA_EVENT_DOWNLOAD_RESULT_BIG_PICTURE_WINDOW = "_LAIXIA_EVENT_DOWNLOAD_RESULT_BIG_PICTURE_WINDOW"
_LAIXIA_EVENT_DOWNLOAD_APPLEDISMISS_WINDOW = "_LAIXIA_EVENT_DOWNLOAD_APPLEDISMISS_WINDOW" --解散

-- 通用图片下载
_LAIXIA_EVENT_DOWNLOADNORMAL_PIC_WINDOW = "_LAIXIA_EVENT_DOWNLOADNORMAL_PIC_WINDOW"

--活动图片下载
_LAIXIA_EVENT_DOWNLOAD_ACTIVITY_WINDOW = "_LAIXIA_EVENT_DOWNLOAD_ACTIVITY_WINDOW"

--轮播图片下载
_LAIXIA_EVENT_DOWNLOAD_LUNBO_WINDOW = "_LAIXIA_EVENT_DOWNLOAD_LUNBO_WINDOW"

--活动页面
_LAIXIA_EVENT_SHOW_ACTIVITY_WINDOW="_LAIXIA_EVENT_SHOW_ACTIVITY_WINDOW"

-- 发送快速开始请求
_LAIXIA_EVENT_SEND_QUICKGAME_WINDOW = "_LAIXIA_EVENT_SEND_QUICKGAME_WINDOW"

--房间请求
_LAIXIA_EVENT_SEND_ROOM_WINDOW = "_LAIXIA_EVENT_SEND_ROOM_WINDOW"


--显示选择提示框
_LAIXIA_EVENT_SHOW_CUEWORDSSELECT_WINDOW = "_LAIXIA_EVENT_SHOW_CUEWORDSSELECT_WINDOW"
_LAIXIA_EVENT_HIDE_CUEWORDSSELECT_WINDOW = "_LAIXIA_EVENT_HIDE_CUEWORDSSELECT_WINDOW"

--  房间牌桌结算显示
_LAIXIA_EVENT_SHOW_TABLERESULT_WINDOW = "_LAIXIA_EVENT_SHOW_TABLERESULT_WINDOW"
_LAIXIA_EVENT_HIDE_TABLERESULT_WINDOW = "_LAIXIA_EVENT_HIDE_TABLERESULT_WINDOW"
_LAIXIA_EVENT_IS_GAOONSELFBUILDING = "_LAIXIA_EVENT_IS_GAOONSELFBUILDING"

--自建桌大结算
_LAIXIA_EVENT_SHOW_SELFBUILDINGRESULT_WINDOW = "_LAIXIA_EVENT_SHOW_SELFBUILDINGRESULT_WINDOW"
_LAIXIA_EVENT_HIDE_SELFBUILDINGRESULT_WINDOW = "_LAIXIA_EVENT_HIDE_SELFBUILDINGRESULT_WINDOW"
_LAIXIA_EVENT_SELFBUILDING_REWARDS = "_LAIXIA_EVENT_SELFBUILDING_REWARDS" 

--更新牌桌结算里面的任务列表
_LAIXIA_EVENT_UPDATE_TASKLISTTABLE_WINDOW = "_LAIXIA_EVENT_UPDATE_TASKLISTTABLE_WINDOW"

-- 结算
_LAIXIA_EVENT_SHOW_TABLERESULT_WINDOWBACK = "_LAIXIA_EVENT_SHOW_TABLERESULT_WINDOWBACK"
_LAIXIA_EVENT_HIDE_TABLERESULT_WINDOWBACK = "_LAIXIA_EVENT_HIDE_TABLERESULT_WINDOWBACK"

--添加流局动画
_LAIXIA_EVENT_SHOW_ANIMATION_LIUJU = "_LAIXIA_EVENT_SHOW_ANIMATION_LIUJU"

--牌桌阶段同步消息
_LAIXIA_EVENT_UPDATE_SYNTABLESTAGE_WINDOW = "_LAIXIA_EVENT_UPDATE_SYNTABLESTAGE_WINDOW"

-- 房间降级
_LAIXIA_EVENT_SHOW_ROOMDEMOTE_WINDOW = "_LAIXIA_EVENT_SHOW_ROOMDEMOTE_WINDOW"

-- 购买记牌器界面
_LAIXIA_EVENT_SHOW_BUYRECORDER_WINDOW = "_LAIXIA_EVENT_SHOW_BUYRECORDER_WINDOW"
_LAIXIA_EVENT_HIDE_BUYRECORDER_WINDOW = "_LAIXIA_EVENT_HIDE_BUYRECORDER_WINDOW"
_LAIXIA_EVENT_CHANGE_BUYRECORDER_WINDOW = "_LAIXIA_EVENT_CHANGE_BUYRECORDER_WINDOW"

--牌桌界面
_LAIXIA_EVENT_SHOW_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_SHOW_LANDLORDTABLE_WINDOW"
--牌桌同步
_LAIXIA_EVENT_INITSYN_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_INITSYN_LANDLORDTABLE_WINDOW"
--发牌
_LAIXIA_EVENT_DEAL_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_DEAL_LANDLORDTABLE_WINDOW"
--属性同步
_LAIXIA_EVENT_ATTRICHANGE_LANDLORDTABLE_WINDOWS = "_LAIXIA_EVENT_ATTRICHANGE_LANDLORDTABLE_WINDOWS"

--发牌动画OK
_LAIXIA_EVENT_DEALANI_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_DEALANI_LANDLORDTABLE_WINDOW"
-- 清空牌桌
_LAIXIA_EVENT_CLEAR_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_CLEAR_LANDLORDTABLE_WINDOW"
-- 出牌
_LAIXIA_EVENT_PLAY_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_PLAY_LANDLORDTABLE_WINDOW"
-- 叫地主
_LAIXIA_EVENT_CALL_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_CALL_LANDLORDTABLE_WINDOW"
-- 托管
_LAIXIA_EVENT_MANDATE_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_MANDATE_LANDLORDTABLE_WINDOW"
-- 继续游戏
_LAIXIA_EVENT_CONTINUE_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_CONTINUE_LANDLORDTABLE_WINDOW"
-- 明牌
_LAIXIA_EVENT_SHOWCARD_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_SHOWCARD_LANDLORDTABLE_WINDOW"
-- 牌桌阶段
_LAIXIA_EVENT_STATE_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_STATE_LANDLORDTABLE_WINDOW"
-- 站内玩家信息
_LAIXIA_EVENT_PLAYER_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_PLAYER_LANDLORDTABLE_WINDOW"
-- 牌桌同步
_LAIXIA_EVENT_SYNC_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_SYNC_LANDLORDTABLE_WINDOW"
--清除牌桌内数据
_LAIXIA_EVENT_CLEAR_DATELANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_CLEAR_DATELANDLORDTABLE_WINDOW"
--播放春天动画特效
_LAIXIA_EVENT_SPRING_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_SPRING_LANDLORDTABLE_WINDOW"

--继续游戏时回调调整金币
_LAIXIA_EVENT_CONTINUEGOLD_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_CONTINUEGOLD_LANDLORDTABLE_WINDOW"
--继续游戏金币不足的情况，给牌桌发送此情况的消息
_LAIXIA_EVENT_NOMONEY_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_NOMONEY_LANDLORDTABLE_WINDOW"
--设置出牌消息
_LAIXIA_EVENT_COMPUTECART_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_COMPUTECART_LANDLORDTABLE_WINDOW"

--点击开始回调
_LAIXIA_EVENT_BEGIN_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_BEGIN_LANDLORDTABLE_WINDOW"

--发送离开房间消息
_LAIXIA_EVENT_EXITROOM_LANDLORDTABLE_WINDOW = "_LAIXIA_EVENT_EXITROOM_LANDLORDTABLE_WINDOW"

-- 比赛相关界面
--进入比赛列表
_LAIXIA_EVENT_GAMELIST_GOGAMELIST="_LAIXIA_EVENT_GAMELIST_GOGAMELIST"
_LAIXIA_EVENT_SENDRENMAN_GOGAMELIST = "_LAIXIA_EVENT_SENDRENMAN_GOGAMELIST"
_LAIXIA_EVENT_SENDDINGSHI_GOGAMELIST = "_LAIXIA_EVENT_SENDDINGSHI_GOGAMELIST"
--显示比赛列表
_LAIXIA_EVENT_SHOW_MATCHLIST_WINDOW="_LAIXIA_EVENT_SHOW_MATCHLIST_WINDOW"
_LAIXIA_EVENT_HIDE_MATCHLIST_WINDOW="_LAIXIA_EVENT_HIDE_MATCHLIST_WINDOW"
_LAIXIA_EVENT_UPDATE_MATCHSTATE_WINDOW_WINDOW = "_LAIXIA_EVENT_UPDATE_MATCHSTATE_WINDOW_WINDOW"

--更新列表页中比赛的状态
_LAIXIA_EVENT_UPDATE_MATCHSTATE_WINDOW="_LAIXIA_EVENT_UPDATE_MATCHSTATE_WINDOW"
--比赛详情
_LAIXIA_EVENT_SHOW_MATCHLISTDETAIL_WINDOW="_LAIXIA_EVENT_SHOW_MATCHLISTDETAIL_WINDOW"
_LAIXIA_EVENT_HIDE_MATCHLISTDETAIL_WINDOW="_LAIXIA_EVENT_HIDE_MATCHLISTDETAIL_WINDOW"
--进入比赛详情
_LAIXIA_EVENT_MATCHDETAIL_WINDOW ="_LAIXIA_EVENT_MATCHDETAIL_WINDOW"

--参加比赛
_LAIXIA_EVENT_SHOW_MATCHJOIN_WINDOW = "_LAIXIA_EVENT_SHOW_MATCHJOIN_WINDOW"
_LAIXIA_EVENT_HIDE_MATCHJOIN_WINDOW = "_LAIXIA_EVENT_HIDE_MATCHJOIN_WINDOW"
_LAIXIA_EVENT_NOSHOW_MATCHJOIN_WINDOW = "_LAIXIA_EVENT_NOSHOW_MATCHJOIN_WINDOW"
-- 确认参加比赛
_LAIXIA_EVENT_MAST_MATCHJOIN_WINDOW = "_LAIXIA_EVENT_MAST_MATCHJOIN_WINDOW"
--确认参加界面的按钮更新
_LAIXIA_EVENT_JOIN_MATCHJOIN_WINDOW="_LAIXIA_EVENT_JOIN_MATCHJOIN_WINDOW"
_LAIXIA_EVENT_QUIT_MATCHJOIN_WINDOW ="_LAIXIA_EVENT_QUIT_MATCHJOIN_WINDOW"
--报名阶段退赛
_LAIXIA_EVENT_WITHDRAW_MATCHJOIN_WINDOW ="_LAIXIA_EVENT_WITHDRAW_MATCHJOIN_WINDOW"
--注册比赛
_LAIXIA_EVENT_REGISTER_MATCH_WINDOW = "_LAIXIA_EVENT_REGISTER_MATCH_WINDOW"
-- 比赛进度条
_LAIXIA_EVENT_UPDATE_PROGRESSBARMATCH_WINDOW="_LAIXIA_EVENT_UPDATE_PROGRESSBARMATCH_WINDOW"
--比赛等待界面
_LAIXIA_EVENT_SHOW_WAITSTATE_WINDOW="_LAIXIA_EVENT_SHOW_WAITSTATE_WINDOW"
_LAIXIA_EVENT_HIDE_WAITSTATE_WINDOW="_LAIXIA_EVENT_HIDE_WAITSTATE_WINDOW"
-- 比赛第一名奖励
_LAIXIA_EVENT_MATCHBROADCAST_WINDOW ="_LAIXIA_EVENT_MATCHBROADCAST_WINDOW"
--比赛中间等待界面
_LAIXIA_EVENT_SHIOW_MATCHWAITLOADING_WINDOW ="_LAIXIA_EVENT_SHIOW_MATCHWAITLOADING_WINDOW"
_LAIXIA_EVENT_HIDE_MATCHWAITLOADING_WINDOW ="_LAIXIA_EVENT_HIDE_MATCHWAITLOADING_WINDOW"
_LAIXIA_EVENT_UPDATE_MATCHWAITLOADING_WINDOW ="_LAIXIA_EVENT_UPDATE_MATCHWAITLOADING_WINDOW"
--显示比赛排行
_LAIXIA_EVENT_SHOW_MATCHRANK_WINDOW="_LAIXIA_EVENT_SHOW_MATCHRANK_WINDOW"
_LAIXIA_EVENT_HIDE_MATCHRANK_WINDOW ="_LAIXIA_EVENT_HIDE_MATCHRANK_WINDOW"
_LAIXIA_EVENT_GOMATCHRANK_WINDOW= "_LAIXIA_EVENT_GOMATCHRANK_WINDOW"
--显示比赛结果
_LAIXIA_EVENT_SHOW_MATCHRESULT_WINDOW="_LAIXIA_EVENT_SHOW_MATCHRESULT_WINDOW"
_LAIXIA_EVENT_HIDE_MATCHRESULT_WINDOW ="_LAIXIA_EVENT_HIDE_MATCHRESULT_WINDOW"
--比赛阶段闪字
_LAIXIA_EVENT_SHOW_MATCHFLICKERWORDS_WINDOW="_LAIXIA_EVENT_SHOW_MATCHFLICKERWORDS_WINDOW"
_LAIXIA_EVENT_HIDE_MATCHFLICKERWORDS_WINDOW= "_LAIXIA_EVENT_HIDE_MATCHFLICKERWORDS_WINDOW"
_LAIXIA_EVENT_ADD_MATCHFLICKERWORDS_WINDOW="_LAIXIA_EVENT_ADD_MATCHFLICKERWORDS_WINDOW"
--比赛结算继续比赛
_LAIXIA_EVENT_CONTINUEMATCH_WINDOW="_LAIXIA_EVENT_CONTINUEMATCH_WINDOW"
--复活界面失败
_LAIXIA_EVENT_SHOW_MATCHEASTER_WINDOW="_LAIXIA_EVENT_SHOW_MATCHEASTER_WINDOW"
_LAIXIA_EVENT_HIDE_MATCHEASTER_WINDOW="_LAIXIA_EVENT_HIDE_MATCHEASTER_WINDOW"
_LAIXIA_EVENT_MATCHEASTERRESULT_WINDOW ="_LAIXIA_EVENT_MATCHEASTERRESULT_WINDOW"

--微信未绑定界面ui
_LAIXIA_EVENT_SHOW_TISHIYUWECHAT_WINDOW = "_LAIXIA_EVENT_SHOW_TISHIYUWECHAT_WINDOW"
_LAIXIA_EVENT_HIDE_TISHIYUWECHAT_WINDOW = "_LAIXIA_EVENT_HIDE_TISHIYUWECHAT_WINDOW"



--显示等待文字动画
_LAIXIA_EVENT_SHOW_WAITTINGCARTOON_WINDOW = "_LAIXIA_EVENT_SHOW_WAITTINGCARTOON_WINDOW"


--显示隐藏 android的中间界面
_LAIXIA_EVENT_SHOW_ANDROIDBACKTK_WINDOW = "_LAIXIA_EVENT_SHOW_ANDROIDBACKTK_WINDOW"



--大厅小游戏解锁信息
_LAIXIA_EVENT_UPDATE_SMALLGAMELOCK_WINDOW="_LAIXIA_EVENT_UPDATE_SMALLGAMELOCK_WINDOW"

-- 龙虎斗
_LAIXIA_EVENT_SHOW_DRAGON_WINDOW = "_LAIXIA_EVENT_SHOW_DRAGON_WINDOW"
_LAIXIA_EVENT_DRAGON_RESULT_WINDOW = "_LAIXIA_EVENT_DRAGON_RESULT_WINDOW"
_LAIXIA_EVENT_DRAGON_STATESYNC_WINDOW = "_LAIXIA_EVENT_DRAGON_STATESYNC_WINDOW"
_LAIXIA_EVENT_DRAGON_CLEARING_WINDOW = "_LAIXIA_EVENT_DRAGON_CLEARING_WINDOW"
_LAIXIA_EVENT_HIDE_RESULT_WINDOW = "_LAIXIA_EVENT_HIDE_RESULT_WINDOW" --隐藏结算界面
_LAIXIA_EVENT_DRAGON_BET_WINDOW = "_LAIXIA_EVENT_DRAGON_BET_WINDOW"
_LAIXIA_EVENT_DRAGON_EXIT_WINDOW = "_LAIXIA_EVENT_DRAGON_EXIT_WINDOW"
_LAIXIA_EVENT_DRAGON_RECORD_WINDOW = "_LAIXIA_EVENT_DRAGON_RECORD_WINDOW"
_LAIXIA_EVENT_DRAGON_UPDATE_WINDOW = "_LAIXIA_EVENT_DRAGON_UPDATE_WINDOW"
_LAIXIA_EVENT_DRAGON_QUIT_TABLE = "_LAIXIA_EVENT_DRAGON_QUIT_TABLE"
--显示结算动画
_LAIXIA_EVENT_SHOW_RESULTANIMATION =  "_LAIXIA_EVENT_SHOW_RESULTANIMATION"
--显示规则介绍
_LAIXIA_EVENT_DRAGON_SHOW_RULE = "_LAIXIA_EVENT_DRAGON_SHOW_RULE"
_LAIXIA_EVENT_DRAGON_HIDE_RULE = "_LAIXIA_EVENT_DRAGON_HIDE_RULE"
--桃李卡显示
_LAIXIA_EVENT_DRAGON_SHOW_TAOLIKA = "_LAIXIA_EVENT_DRAGON_SHOW_TAOLIKA"
_LAIXIA_EVENT_DRAGON_HIDE_TAOLIKA = "_LAIXIA_EVENT_DRAGON_HIDE_TAOLIKA"
_LAIXIA_EVENT_DRAGON_TAOLIKA_MESG = "_LAIXIA_EVENT_DRAGON_TAOLIKA_MESG"--赠送桃李卡返回消息

--------------------------------------------------------------------------------------------------
--万人牛牛界面
_LAIXIA_EVENT_WANRENIUNIU_SHOW_MAINWINDOW = "_LAIXIA_EVENT_WANRENIUNIU_SHOW_MAINWINDOW"
_LAIXIA_EVENT_WANRENIUNIU_ADDBET = "_LAIXIA_EVENT_WANRENIUNIU_ADDBET"
_LAIXIA_EVENT_WANRENIUNIU_UPDATECHIP = "_LAIXIA_EVENT_WANRENIUNIU_UPDATECHIP"
_LAIXIA_EVENT_WANRENNIUNIU_SHOW_RESULT = "_LAIXIA_EVENT_WANRENNIUNIU_SHOW_RESULT"
_LAIXIA_EVENT_WANRENNIUNIU_INITHISTORY = "_LAIXIA_EVENT_WANRENNIUNIU_INITHISTORY"
_LAIXIA_EVENT_WANRENNIUNIU_ADDCHIP = "_LAIXIA_EVENT_WANRENNIUNIU_ADDCHIP"
--万人牛牛加倍界面
_LAIXIA_EVENT_WANRENNIUNIU_SHOW_DOUBLEWINDOW = "_LAIXIA_EVENT_WANRENNIUNIU_SHOW_DOUBLEWINDOW"
_LAIXIA_EVENT_WANRENNIUNIU_HIDE_DOUBLEWINDOW = "_LAIXIA_EVENT_WANRENNIUNIU_HIDE_DOUBLEWINDOW"
_LAIXIA_EVENT_WANRENNIUNIU_SHOW_OPENCADS = "_LAIXIA_EVENT_WANRENNIUNIU_SHOW_OPENCADS"
_LAIXIA_EVENT_WANRENNIUNIU_HALF_CHIPRET = "_LAIXIA_EVENT_WANRENNIUNIU_HALF_CHIPRET"


---------------------------------------------------------------------------------------------------
--水果机
_LAIXIA_EVENT_FRUITTABBLE_SHOW_WINDOW  = "_LAIXIA_EVENT_FRUITTABBLE_SHOW_WINDOW"
_LAIXIA_EVENT_FRUITTABBLE_HIDE_WINDOW  = "_LAIXIA_EVENT_FRUITTABBLE_HIDE_WINDOW"
_LAIXIA_EVENT_FRUITTABBLE_GAMESTART = "_LAIXIA_EVENT_FRUITTABBLE_GAMESTART"   --游戏开始
_LAIXIA_EVENT_FRUITTABBLE_UPDATE_ALLCHIP = "_LAIXIA_EVENT_FRUITTABBLE_UPDATE_ALLCHIP"   --刷新筹码
_LAIXIA_EVENT_FRUITTABBLE_UPDATE_MYCHIP = "_LAIXIA_EVENT_FRUITTABBLE_UPDATE_MYCHIP"   --刷新我的筹码
_LAIXIA_EVENT_FRUITTABBLE_SHOWRESULTANIMATION = "_LAIXIA_EVENT_FRUITTABBLE_SHOWRESULTANIMATION"   --显示结算动画
_LAIXIA_EVENT_FRUITTABBLE_SHOWRESULT = "_LAIXIA_EVENT_FRUITTABBLE_SHOWRESULT"   --显示结算
_LAIXIA_EVENT_FRUITTABBLE_SHOWRESULT_MSG = "_LAIXIA_EVENT_FRUITTABBLE_SHOWRESULT_MSG"   --显示结算信息

----------------------------------------------------------------------------------------------
-- 三张牌相关
-- 显示三张牌界面
_LAIXIA_EVENT_SHOW_MCKITINIT_WINDOW	= "_LAIXIA_EVENT_SHOW_MCKITINIT_WINDOW"
_LAIXIA_EVENT_HIDE_MCKITINIT_WINDOW	= "_LAIXIA_EVENT_HIDE_MCKITINIT_WINDOW"

-- 三张牌toast显示
_LAIXIA_EVENT_SHOW_MCKITTOAST_WINDOW 			= "_LAIXIA_EVENT_SHOW_MCKITTOAST_WINDOW"
_LAIXIA_EVENT_HIDE_MCKITTOAST_WINDOW 			= "_LAIXIA_EVENT_HIDE_MCKITTOAST_WINDOW"


-- 三张牌led
_LAIXIA_EVENT_MCKIT_GUIDANCE_WINDOW       = "_LAIXIA_EVENT_MCKIT_GUIDANCE_WINDOW"
_LAIXIA_EVENT_SHOW_MCKITGUIDANCE_WINDOW      = "_LAIXIA_EVENT_SHOW_MCKITGUIDANCE_WINDOW"

-- 三张牌entergame
_LAIXIA_EVENT_MCKIT_ENTER_WINDOW 		= "_LAIXIA_EVENT_MCKIT_ENTER_WINDOW"
-- 三张牌坐下
_LAIXIA_EVENT_MCKIT_SITDOWN_WINDOW 		= "_LAIXIA_EVENT_MCKIT_SITDOWN_WINDOW"
-- 三张牌站起
_LAIXIA_EVENT_MCKIT_STANDUP_WINDOW 		= "_LAIXIA_EVENT_MCKIT_STANDUP_WINDOW"
-- 三张牌换桌
_LAIXIA_EVENT_MCKIT_CHANGEDESK_WINDOW 		= "_LAIXIA_EVENT_MCKIT_CHANGEDESK_WINDOW"
-- 三张牌游戏开始
_LAIXIA_EVENT_MCKIT_START_WINDOW 		= "_LAIXIA_EVENT_MCKIT_START_WINDOW"
-- 三张牌游戏结果
_LAIXIA_EVENT_MCKIT_RESULT_WINDOW 		= "_LAIXIA_EVENT_MCKIT_RESULT_WINDOW"
-- 三张牌游戏结束
_LAIXIA_EVENT_MCKIT_GAMEOVER_WINDOW 		= "_LAIXIA_EVENT_MCKIT_GAMEOVER_WINDOW"
-- 三张牌开始操作
_LAIXIA_EVENT_MCKIT_OPTBEGIN_WINDOW 		= "_LAIXIA_EVENT_MCKIT_OPTBEGIN_WINDOW"
-- 三张牌下注
_LAIXIA_EVENT_MCKIT_BET_WINDOW 			= "_LAIXIA_EVENT_MCKIT_BET_WINDOW"
-- 三张牌跟注
_LAIXIA_EVENT_MCKIT_FOLLOW_WINDOW 			= "_LAIXIA_EVENT_MCKIT_FOLLOW_WINDOW"
-- 三张牌看牌
_LAIXIA_EVENT_MCKIT_CARDS_WINDOW 		= "_LAIXIA_EVENT_MCKIT_CARDS_WINDOW"
-- 三张牌比牌
_LAIXIA_EVENT_MCKIT_COMPARE_WINDOW 		= "_LAIXIA_EVENT_MCKIT_COMPARE_WINDOW"
-- 三张牌弃牌
_LAIXIA_EVENT_MCKIT_THROWCARDS_WINDOW 		= "_LAIXIA_EVENT_MCKIT_THROWCARDS_WINDOW"
-- 三张牌show牌
_LAIXIA_EVENT_MCKIT_SHOWCARDS_WINDOW		= "_LAIXIA_EVENT_MCKIT_SHOWCARDS_WINDOW"
-- 三张牌退出
_LAIXIA_EVENT_MCKIT_EXIT_WINDOW 			= "_LAIXIA_EVENT_MCKIT_EXIT_WINDOW"

--兌換提示
_LAIXIA_EVENT_DUIHUAN_SHOW_WINDOW          = "_LAIXIA_EVENT_DUIHUAN_SHOW_WINDOW"

--申请解散房间
_LAIXIA_EVENT_SHOW_APPLYDISMISS_WINDOW = "_LAIXIA_EVENT_SHOW_APPLYDISMISS_WINDOW"
_LAIXIA_EVENT_SHOW_APPLYDISMISS_WINDOW_WINDOW = "_LAIXIA_EVENT_SHOW_APPLYDISMISS_WINDOW_WINDOW"
_LAIXIA_EVENT_UPDATE_APPLYDISMISS_WINDOW = "_LAIXIA_EVENT_UPDATE_APPLYDISMISS_WINDOW"
_LAIXIA_EVENT_HIDE_APPLYDISMISS_WINDOW = "_LAIXIA_EVENT_HIDE_APPLYDISMISS_WINDOW"

--获取版本号
_LAIXIA_EVENT_GETVERSION = "_LAIXIA_EVENT_GETVERSION"

--游戏中获取版本号
_LAIXIA_EVENT_GETVERSIONIN = "_LAIXIA_EVENT_GETVERSIONIN"

--健康提示
_LAIXIA_EVENT_SHOW_COUNSEL_WINDOW = "_LAIXIA_EVENT_SHOW_COUNSEL_WINDOW"

--个人账单
_LAIXIA_EVENT_SHOW_PERSONBILL_WINDOW = "_LAIXIA_EVENT_SHOW_PERSONBILL_WINDOW"
_LAIXIA_EVENT_SHOW_HIDEPERSONBILL_WINDOW = "_LAIXIA_EVENT_SHOW_HILLPERSONBILL_WINDOW"

--温馨提示
_LAIXIA_EVENT_SHOW_EXCHANGETISHI_WINDOW = "_LAIXIA_EVENT_SHOW_EXCHANGETISHI_WINDOW"

--送来豆
_LAIXIA_EVENT_SHOW_GETLAIDOU = "_LAIXIA_EVENT_SHOW_GETLAIDOU"

-- 红包领取
_LAIXIA_EVENT_SHOW_MONEY_WINDOW = "_LAIXIA_EVENT_SHOW_MONEY_WINDOW"
_LAIXIA_EVENT_SHOW_HIDEMONEY_WINDOW = "_LAIXIA_EVENT_SHOW_HIDEMONEY_WINDOW"

--获取任务列表 登陆时
_LAIXIA_EVENT_SEND_GETTASKLIST = "_LAIXIA_EVENT_SEND_GETTASKLIST"

-- 开发者
-- _LAIXIA_EVENT_SHOW_KAIFAZHE = "_LAIXIA_EVENT_SHOW_KAIFAZHE"

-- 快捷按钮
_LAIXIA_EVENT_SHOW_BUTTONLAYER = "_LAIXIA_EVENT_SHOW_BUTTONLAYER"

-- --隐藏详情界面的报名花费窗口
-- _LAIXIA_EVENT_HIDE_COSTWINDOW = "_LAIXIA_EVENT_HIDE_COSTWINDOW"


