
_ID_HTTP_CONNECTING = 2

--牌型的字典

_ID_DICT_TYPE_TEN_THOUSAND = 13 --万
_ID_DICT_TYPE_HUNDRED_MILLION = 14 --亿


--弹窗提示

_ID_DICT_TYPE_NOTIFY_OFFLINE = 2002 --通知下线
_ID_DICT_TYPE_CONVERSIONCODE_INVALID = 2003
_ID_DICT_TYPE_CODE_CONVERSIONCODE_INVALID = 2004
_ID_DICT_TYPE_CODE_HAVE_TO_RECEIVE = 2005
_ID_DICT_TYPE_CAN_MODIFY_ONE = 2006
_ID_DICT_TYPE_NICKNAME_LIMIT = 2007


_ID_DICT_TYPE_CONNECT_ERROR = 2023  --连接失败，点击确定重试
_ID_DICT_TYPE_NO_NET = 2024
_ID_DICT_TYPE_CONNECT_TIMEOUT = 2025
_ID_DICT_TYPE_NET_ERROR_LOGIN = 2026          --

_ID_DICT_TYPE_WAITING_FOR_SWITCH =2028   --正在切换中，请稍后

